"""empty message

Revision ID: 089b9ae4bb8b
Revises: 2a1afc883df4
Create Date: 2019-09-26 10:38:36.659161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089b9ae4bb8b'
down_revision = '2a1afc883df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('progress', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'progress')
    # ### end Alembic commands ###
