"""empty message

Revision ID: 2a1afc883df4
Revises: 82a51ff3b0a5
Create Date: 2019-09-25 18:06:41.740929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1afc883df4'
down_revision = '82a51ff3b0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_photo')
    # ### end Alembic commands ###
