"""empty message

Revision ID: 82a51ff3b0a5
Revises: 07e16fec9869
Create Date: 2019-09-25 18:02:45.348809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a51ff3b0a5'
down_revision = '07e16fec9869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_image')
    # ### end Alembic commands ###
